export const extionsIconsPaths: Record<string, string> = {
  // ** Files
  tsx: "/icons/react_ts",
  js: "/icons/javascript",
  jsx: "/icons/react",
  html: "/icons/html",
  css: "/icons/css",
  ts: "/icons/typescript",
  json: "/icons/json",
  md: "/icons/markdown",
  xml: "/icons/xml",
  yml: "/icons/yaml",
  yaml: "/icons/yaml",
  png: "/icons/image",
  jpg: "/icons/image",
  jpeg: "/icons/image",
  gif: "/icons/image",
  svg: "/icons/image",
  pdf: "/icons/pdf",
  txt: "/icons/text",
  csv: "/icons/csv",

  // ** Folders
  node_modules: "/icons/folder-node",
  public: "/icons/folder-public",
  src: "/icons/folder-src",
  components: "/icons/folder-components",
  assets: "/icons/folder-assets",
  styles: "/icons/folder-styles",
  utils: "/icons/folder-utils",
  config: "/icons/folder-config",
  dist: "/icons/folder-dist",
  build: "/icons/folder-build",
};
